### ISSUE TITLE
Can Cicero be programmed to run a batch file or a script at the end of each sequence?

### ISSUE THREAD

**Issue by emorell96** [akeshet/Cicero-Word-Generator#29]
Hi,

I am wondering if Cicero can do this. It would be interesting when we have to upload a waveform to a remote instrument through a VISA command and we cannot upload it through GPIB.

Thank you!

**Comment by akeshet** [comment]
Sorry for the delayed reply. This feature sounds like something that wouldn't be overly difficult to implement. But note that Cicero is currently in a state of being community-maintained. Please join the users group at https://groups.google.com/g/cicero-word-generator-users to discuss features or tips for working on the code.
